namespace _66SMS.Contracts.Enumerations
{
    public enum ErrorCodes
    {
        #region Common
        ERR_VALIDATION_FAILED,
        ERR_NOT_FOUND,
        ERR_SERVER_ERROR,
        ERR_BAD_REQUEST,
        ERR_UNAUTHORIZED,
        ERR_FORBIDDEN,
        ERR_CONFLICT,
        #endregion

        #region ERR_AUTH
        ERR_AUTH_INVALID_CREDENTIALS,
        ERR_AUTH_TOKEN_EXPIRED,
        ERR_AUTH_TOKEN_INVALID,
        ERR_AUTH_REFRESH_TOKEN_EXPIRED,
        ERR_AUTH_REFRESH_TOKEN_INVALID,
        #endregion

        #region User & Role & Permission
        ERR_USER_NOT_FOUND,
        ERR_USER_INVALID,
        ERR_USER_ALREADY_EXISTS,
        ERR_USER_INVALID_PASSWORD,
        ERR_USER_ACCOUNT_LOCKED,
        ERR_USER_ACCOUNT_INACTIVE,
        ERR_ROLE_NOT_FOUND,
        ERR_ROLE_INVALID,
        ERR_PERMISSION_NOT_FOUND,
        ERR_PERMISSION_INVALID,
        ERR_USER_ROLE_NOT_FOUND,
        ERR_USER_ROLE_INVALID,
        ERR_ROLE_PERMISSION_NOT_FOUND,
        ERR_ROLE_PERMISSION_INVALID,
        ERR_REFRESH_TOKEN_NOT_FOUND,
        ERR_REFRESH_TOKEN_INVALID,
        #endregion
        
        #region Customer & Staff
        ERR_CUSTOMER_NOT_FOUND,
        ERR_CUSTOMER_INVALID,
        ERR_STAFF_NOT_FOUND,
        ERR_STAFF_INVALID,
        #endregion

        #region Shift & WorkSchedule
        ERR_SHIFT_NOT_FOUND,
        ERR_SHIFT_INVALID,
        ERR_SHIFT_PERIOD_NOT_FOUND,
        ERR_SHIFT_PERIOD_INVALID,
        ERR_WORK_SCHEDULE_NOT_FOUND,
        ERR_WORK_SCHEDULE_INVALID,
        #endregion

        #region Product
        ERR_PRODUCT_NOT_FOUND,
        ERR_PRODUCT_INVALID,
        ERR_PRODUCT_CATEGORY_NOT_FOUND,
        ERR_PRODUCT_CATEGORY_INVALID,
        ERR_PRODUCT_IMAGE_NOT_FOUND,
        ERR_PRODUCT_IMAGE_INVALID,
        #endregion

        #region Service
        ERR_SERVICE_NOT_FOUND,
        ERR_SERVICE_INVALID,
        ERR_SERVICE_CATEGORY_NOT_FOUND,
        ERR_SERVICE_CATEGORY_INVALID,
        ERR_SERVICE_IMAGE_NOT_FOUND,
        ERR_SERVICE_IMAGE_INVALID,
        ERR_SERVICE_PRODUCT_NOT_FOUND,
        ERR_SERVICE_PRODUCT_INVALID,
        #endregion

        #region Booking
        ERR_BOOKING_ROOM_NOT_FOUND,
        ERR_BOOKING_ROOM_INVALID,
        ERR_BOOKING_POSITION_NOT_FOUND,
        ERR_BOOKING_POSITION_INVALID,
        #endregion

        #region Appointment
        ERR_APPOINTMENT_NOT_FOUND,
        ERR_APPOINTMENT_INVALID,
        ERR_APPOINTMENT_SLOT_LOCK_NOT_FOUND,
        ERR_APPOINTMENT_SLOT_LOCK_INVALID,
        ERR_APPOINTMENT_SERVICE_NOT_FOUND,
        ERR_APPOINTMENT_SERVICE_INVALID,
        ERR_APPOINTMENT_PAYMENT_NOT_FOUND,
        ERR_APPOINTMENT_PAYMENT_INVALID,
        ERR_APPOINTMENT_HISTORY_NOT_FOUND,
        ERR_APPOINTMENT_HISTORY_INVALID,
        #endregion

        #region Wallet
        ERR_WALLET_NOT_FOUND,
        ERR_WALLET_INVALID,
        ERR_WALLET_TRANSACTION_NOT_FOUND,
        ERR_WALLET_TRANSACTION_INVALID,
        #endregion

        #region Membership
        ERR_MEMBERSHIP_TIER_NOT_FOUND,
        ERR_MEMBERSHIP_TIER_INVALID,
        ERR_MEMBERSHIP_CARD_NOT_FOUND,
        ERR_MEMBERSHIP_CARD_INVALID,
        ERR_MEMBERSHIP_CARD_HISTORY_NOT_FOUND,
        ERR_MEMBERSHIP_CARD_HISTORY_INVALID,
        #endregion

        #region TimeSlot
        ERR_TIME_SLOT_NOT_FOUND,
        ERR_TIME_SLOT_INVALID,
        #endregion

        #region Salon
        ERR_SALON_NOT_FOUND,
        ERR_SALON_INVALID,
        ERR_SALON_CODE_EXISTED,
        ERR_STAFF_SALON_NOT_FOUND,
        ERR_STAFF_SALON_INVALID,
        #endregion
    }
}