namespace _66SMS.Contracts.Enumerations
{
    public enum ErrorCodes
    {
        #region Common
        ERR_VALIDATION_FAILED,
        ERR_NOT_FOUND,
        ERR_SERVER_ERROR,
        ERR_BAD_REQUEST,
        ERR_UNAUTHORIZED,
        ERR_FORBIDDEN,
        ERR_CONFLICT,
        #endregion

        #region ERR_AUTH
        ERR_AUTH_INVALID_CREDENTIALS,
        ERR_AUTH_TOKEN_EXPIRED,
        ERR_AUTH_TOKEN_INVALID,
        ERR_AUTH_REFRESH_TOKEN_EXPIRED,
        ERR_AUTH_REFRESH_TOKEN_INVALID,
        ERR_AUTH_ACCOUNT_LOCKED,
        ERR_AUTH_NO_ROLE,
        ERR_AUTH_TOKEN_REVOKED,
        #endregion

        #region OTP
        ERR_OTP_EMAIL_NOT_FOUND,
        ERR_OTP_EMAIL_ALREADY_VERIFIED,
        ERR_OTP_NOT_SENT,
        ERR_OTP_INVALID_OR_EXPIRED,
        ERR_OTP_WRONG_CODE,
        #endregion

        #region User & Role & Permission
        ERR_USER_NOT_FOUND,
        ERR_USER_INVALID,
        ERR_USER_ALREADY_EXISTS,
        ERR_USER_INVALID_PASSWORD,
        ERR_USER_ACCOUNT_LOCKED,
        ERR_USER_ACCOUNT_INACTIVE,
        ERR_ROLE_NOT_FOUND,
        ERR_ROLE_INVALID,
        ERR_ROLE_NAME_EXISTED,
        ERR_PERMISSION_NOT_FOUND,
        ERR_PERMISSION_INVALID,
        ERR_PERMISSION_NAME_EXISTED,
        ERR_USER_ROLE_NOT_FOUND,
        ERR_USER_ROLE_INVALID,
        ERR_ROLE_PERMISSION_NOT_FOUND,
        ERR_ROLE_PERMISSION_INVALID,
        ERR_REFRESH_TOKEN_NOT_FOUND,
        ERR_REFRESH_TOKEN_INVALID,
        #endregion
        
        #region Customer & Staff
        ERR_CUSTOMER_NOT_FOUND,
        ERR_CUSTOMER_INVALID,
        ERR_STAFF_NOT_FOUND,
        ERR_STAFF_INVALID,
        ERR_STAFF_BOOKING_NOT_FOUND,
        ERR_STAFF_SALON_MANAGER_NOT_FOUND,
        #endregion

        #region Shift & WorkSchedule
        ERR_SHIFT_NOT_FOUND,
        ERR_SHIFT_INVALID,
        ERR_SHIFT_PERIOD_NOT_FOUND,
        ERR_SHIFT_PERIOD_INVALID,
        ERR_WORK_SCHEDULE_NOT_FOUND,
        ERR_WORK_SCHEDULE_INVALID,
        ERR_WORK_SCHEDULE_DUPLICATE,
        #endregion

        #region Product
        ERR_PRODUCT_NOT_FOUND,
        ERR_PRODUCT_INVALID,
        ERR_PRODUCT_CATEGORY_NOT_FOUND,
        ERR_PRODUCT_CATEGORY_INVALID,
        ERR_PRODUCT_IMAGE_NOT_FOUND,
        ERR_PRODUCT_IMAGE_INVALID,
        #endregion

        #region Service
        ERR_SERVICE_NOT_FOUND,
        ERR_SERVICE_INVALID,
        ERR_SERVICE_CATEGORY_NOT_FOUND,
        ERR_SERVICE_CATEGORY_INVALID,
        ERR_SERVICE_IMAGE_NOT_FOUND,
        ERR_SERVICE_IMAGE_INVALID,
        ERR_SERVICE_PRODUCT_NOT_FOUND,
        ERR_SERVICE_PRODUCT_INVALID,
        #endregion

        #region Booking
        ERR_BOOKING_ROOM_NOT_FOUND,
        ERR_BOOKING_ROOM_INVALID,
        ERR_BOOKING_POSITION_NOT_FOUND,
        ERR_BOOKING_POSITION_INVALID,
        #endregion

        #region Appointment
        ERR_APPOINTMENT_NOT_FOUND,
        ERR_APPOINTMENT_INVALID,
        ERR_APPOINTMENT_SLOT_LOCK_NOT_FOUND,
        ERR_APPOINTMENT_SLOT_LOCK_INVALID,
        ERR_APPOINTMENT_SERVICE_NOT_FOUND,
        ERR_APPOINTMENT_SERVICE_INVALID,
        ERR_APPOINTMENT_PAYMENT_NOT_FOUND,
        ERR_APPOINTMENT_PAYMENT_INVALID,
        ERR_APPOINTMENT_HISTORY_NOT_FOUND,
        ERR_APPOINTMENT_HISTORY_INVALID,
        ERR_APPOINTMENT_SLOT_FULL,
        ERR_APPOINTMENT_ALREADY_PAID,
        ERR_APPOINTMENT_DEPOSIT_ALREADY_PAID,
        ERR_APPOINTMENT_NOT_DEPOSITED_YET,
        ERR_APPOINTMENT_NOT_WAITING_DEPOSIT,
        ERR_APPOINTMENT_NO_REMAINING_AMOUNT,
        ERR_APPOINTMENT_INVALID_PAYMENT_METHOD,
        ERR_APPOINTMENT_ALREADY_THIS_STATUS,
        ERR_APPOINTMENT_CANCELLED,
        ERR_APPOINTMENT_CANNOT_POSTPONE,
        ERR_APPOINTMENT_STAFF_NOT_IN_SALON,
        ERR_APPOINTMENT_MIN_ONE_SERVICE,
        #endregion

        #region Wallet
        ERR_WALLET_NOT_FOUND,
        ERR_WALLET_INVALID,
        ERR_WALLET_TRANSACTION_NOT_FOUND,
        ERR_WALLET_TRANSACTION_INVALID,
        ERR_WALLET_INVALID_AMOUNT,
        ERR_WALLET_INSUFFICIENT_BALANCE,
        #endregion

        #region Payment
        ERR_PAYMENT_TRANSACTION_FAILED,
        ERR_PAYMENT_ORDER_NOT_FOUND,
        #endregion

        #region Membership
        ERR_MEMBERSHIP_TIER_NOT_FOUND,
        ERR_MEMBERSHIP_TIER_INVALID,
        ERR_MEMBERSHIP_CARD_NOT_FOUND,
        ERR_MEMBERSHIP_CARD_INVALID,
        ERR_MEMBERSHIP_CARD_HISTORY_NOT_FOUND,
        ERR_MEMBERSHIP_CARD_HISTORY_INVALID,
        #endregion

        #region TimeSlot
        ERR_TIME_SLOT_NOT_FOUND,
        ERR_TIME_SLOT_INVALID,
        #endregion

        #region Salon
        ERR_SALON_NOT_FOUND,
        ERR_SALON_INVALID,
        ERR_SALON_CODE_EXISTED,
        ERR_STAFF_SALON_NOT_FOUND,
        ERR_STAFF_SALON_INVALID,
        #endregion

        #region TreatmentCourse
        ERR_TREATMENT_COURSE_NOT_FOUND,
        ERR_TREATMENT_COURSE_INVALID,
        #endregion

        #region Certificate
        ERR_CERTIFICATE_TYPE_NOT_FOUND,
        ERR_CERTIFICATE_TYPE_INVALID,
        ERR_CERTIFICATE_TYPE_CODE_EXISTED,
        ERR_STAFF_CERTIFICATE_NOT_FOUND,
        ERR_STAFF_CERTIFICATE_INVALID,
        #endregion

        #region Invoice
        ERR_INVOICE_NOT_FOUND,
        ERR_INVOICE_INVALID,
        ERR_INVOICE_NO_ITEMS,
        ERR_INVOICE_ALREADY_PAID,
        ERR_INVOICE_CANNOT_CANCEL,
        ERR_INVOICE_NOT_ENOUGH_POINTS,
        ERR_INVOICE_ITEM_REF_NOT_FOUND,
        ERR_INVOICE_INSUFFICIENT_STOCK,
        #endregion

        #region Attendance
        ERR_ATTENDANCE_NOT_FOUND,
        ERR_ATTENDANCE_DUPLICATE,
        ERR_ATTENDANCE_NOT_CHECKED_IN,
        ERR_ATTENDANCE_INVALID_STATUS,
        ERR_ATTENDANCE_WORK_SCHEDULE_REQUIRED,
        ERR_KPI_NOT_CONFIGURED,
        #endregion

        #region Payroll
        ERR_PAYROLL_NOT_FOUND,
        ERR_PAYROLL_ALREADY_CONFIRMED,
        ERR_PAYROLL_NO_ATTENDANCE,
        ERR_PAYROLL_INVALID_STANDARD_DAYS,
        #endregion

        #region Promotion
        ERR_PROMOTION_NOT_FOUND,
        ERR_PROMOTION_CODE_EXISTED,
        ERR_PROMOTION_INVALID,
        ERR_PROMOTION_EXPIRED,
        ERR_PROMOTION_INACTIVE,
        ERR_PROMOTION_USAGE_LIMIT,
        ERR_PROMOTION_MIN_ORDER,
        ERR_BOOKING_ROOM_HAS_POSITIONS,
        #endregion

        #region LandingBanner
        ERR_LANDING_BANNER_NOT_FOUND,
        ERR_LANDING_BANNER_INVALID,
        #endregion
    }
}