export const API = {
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
    refreshToken: "/auth/refresh-token",
    register: "/auth/register",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    changePassword: "/auth/change-password",
    sendOtp: "/auth/send-otp",
    verifyOtp: "/auth/verify-otp",
    role: "/auth/role",
    roleAssign: "/auth/role/assign-permission",
    permission: "/auth/permission",
  },
  users: {
    base: "/users",
    me: "/users/me",
    meMembershipCard: "/users/me/membership-card",
    meWallet: "/users/me/wallet",
    meWalletTx: "/users/me/wallet/transactions",
    meWalletTopUpVnPayUrl: "/users/me/wallet/top-up-vnpay-url",
    accounts: "/users/accounts",
  },
  staffs: {
    base: "/staffs",
  },
  customers: "/customer",
  products: "/product",
  productCategories: "/product-category",
  services: "/service",
  serviceCategories: "/service-category",
  serviceProducts: "/service-product",
  shifts: "/shift",
  timeSlots: "/time-slots",
  configAppointments: "/config-appointments",
  bookingPositions: "/booking-positions",
  bookingRooms: "/booking-rooms",
  appointment: "/appointment",
  workSchedule: "/worker-schedule",
  salons: "/salons",
  landingBanners: "/landing-banners",
  staffSalons: "/staff-salons",
  membershipTiers: "/membership-tiers",
  membershipCards: "/membership-cards",
  treatmentCourses: "/treatment-course",
  invoices: "/invoice",
  certificateTypes: "/certificate-type",
  staffCertificates: "/staff-certificate",
  attendances: "/attendance",
  payrolls: "/payroll",
  promotions: "/promotions",
  cashier: {
    daily: "/cashier/daily",
    weekly: "/cashier/weekly",
    onlineAppointments: "/cashier/online-appointments",
    appointment: "/cashier/appointments",
    positions: "/cashier/positions",
    vnpayCreate: "/cashier/vnpay/create-url",
    vnpayReturn: "/cashier/vnpay-return",
    staffAvailability: "/cashier/staff-availability",
  },
  admin: {
    wallets: "/admin/wallets",
  },
  address: {
    provinces: "/address/provinces",
    wards: "/address/wards",
  },
  notifications: {
    base: "/notifications",
    markAllRead: "/notifications/mark-all-read",
  },
  revenue: {
    reportByPeriod: "/admin/revenue/report/by-period",
    reportBySalon: "/admin/revenue/report/by-salon",
    reportByStaff: "/admin/revenue/report/by-staff",
    reportByService: "/admin/revenue/report/by-service",
    exportByPeriod: "/admin/revenue/report/export-by-period",
    exportBySalon: "/admin/revenue/report/export-by-salon",
    exportByStaff: "/admin/revenue/report/export-by-staff",
    exportByService: "/admin/revenue/report/export-by-service",
  },
} as const;
