// Tập trung toàn bộ URL API vào đây.
// Khi backend thay đổi endpoint → chỉ cần sửa ở file này.

export const API = {
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
    refreshToken: "/auth/refresh-token",
    register: "/auth/register",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    changePassword: "/auth/change-password",
    sendOtp: "/auth/send-otp",
    verifyOtp: "/auth/verify-otp",
    role: "/auth/role",
    roleAssign: "/auth/role/assign-permission",
    permission: "/auth/permission",
  },
  users: {
    base: "/users",
    me: "/users/me",
    meMembershipCard: "/users/me/membership-card",
    meWallet: "/users/me/wallet",
    meWalletTx: "/users/me/wallet/transactions",
    accounts: "/users/accounts",
  },
  staffs: {
    base: "/staffs",
  },
  customers: "/customer",
  products: "/product",
  productCategories: "/product-category",
  productImages: "/product-image",
  services: "/service",
  serviceCategories: "/service-category",
  serviceImages: "/service-image",
  serviceProducts: "/service-product",
  shifts: "/shift",
  timeSlots: "/time-slots",
  bookingPositions: "/booking-positions",
  bookingRooms: "/booking-rooms",
  appointment: "/appointment",
  workSchedule: "/worker-schedule",
  salons: "/salons",
  staffSalons: "/staff-salons",
  membershipTiers: "/membership-tiers",
  membershipCards: "/membership-cards",
  treatmentCourses: "/treatment-course",
  invoices: "/invoice",
  certificateTypes: "/certificate-type",
  staffCertificates: "/staff-certificate",
  attendances: "/attendance",
  payrolls: "/payroll",
  promotions: "/promotions",
  cashier: {
    daily: "/cashier/daily",
    onlineAppointments: "/cashier/online-appointments",
    appointment: "/cashier/appointments",
    vnpayCreate: "/cashier/vnpay/create-url",
    vnpayReturn: "/cashier/vnpay-return",
  },
  admin: {
    wallets: "/admin/wallets",
  },
  address: {
    provinces: "/address/provinces",
    wards: "/address/wards",
  },
  media: {
    image: "/media/image",
    images: "/media/images",
  },
} as const;
