<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>_66SMS.Domain</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Abstractions\Events\**" />
    <Compile Remove="Abstractions\Repositories\Mongo\**" />
    <Compile Remove="Abstractions\Services\**" />
    <EmbeddedResource Remove="Abstractions\Events\**" />
    <EmbeddedResource Remove="Abstractions\Repositories\Mongo\**" />
    <EmbeddedResource Remove="Abstractions\Services\**" />
    <None Remove="Abstractions\Events\**" />
    <None Remove="Abstractions\Repositories\Mongo\**" />
    <None Remove="Abstractions\Services\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\66SMS.Contract\66SMS.Contract.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
  </ItemGroup>
</Project>
